# Generated by Django 5.2.3 on 2025-06-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_users_todo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
